KanbanProject/ViewModels/BoardViewModel.cs
using System.Collections.Generic;
using PlanningBoard.Model;

namespace PlanningBoard.ViewModels
{
    public class BoardViewModel
    {
        public List<Column> Columns { get; set; }
        public List<Color> Colors { get; set; }
        public List<Task> Tasks { get; set; }
        public Board Board { get; set; }
    }
}

KanbanProject/ViewModels/BoardsViewModel.cs
using System.Collections.Generic;
using PlanningBoard.Model;

namespace PlanningBoard.ViewModels
{
    public class BoardsViewModel
    {
        public List<UserBoardsViewModel> Boards { get; set; }
    }
}

KanbanProject/ViewModels/UserBoardsViewModel.cs
namespace PlanningBoard.ViewModels
{
    public class UserBoardsViewModel
    {
        public int BoardId { get; set; }
        public string BoardName { get; set; }
        public bool IsAdmin { get; set; }
    }
}

KanbanProject/Controllers/BaseController.cs
using System.Web.Mvc;

namespace PlanningBoard.Controllers
{
    public class BaseController : Controller
    {
        public BaseController()
        {
            ViewBag.Controller = System.Web.HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
        }

        protected bool ToDelete => Request["delete"] != null && Request["delete"] == "delete";

    }
}

KanbanProject/Controllers/BoardController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using PlanningBoard.Infrastructure.Alerts;
using PlanningBoard.Model;
using PlanningBoard.ViewModels;

namespace PlanningBoard.Controllers
{
    public class BoardController : BaseController
    {
        private readonly IBoardRepository _boardRepository;
        private readonly IColumnRepository _columnRepository;
        private readonly IColorRepository _colorRepository;
        private readonly ITaskRepository _taskRepository;

        public BoardController()
        {
            _boardRepository = new BoardRepository();
            _columnRepository = new ColumnRepository();
            _colorRepository = new ColorRepository();
            _taskRepository = new TaskRepository();
        }

        public ActionResult Index(int id)
        {
            var colors = _colorRepository.List();
            var board = _boardRepository.Get(id);
            var columns = _columnRepository.List(board.Id);
            var tasks = _taskRepository.List(id);

            ViewBag.BoardName = _boardRepository.List().Single(b => b.Id==id).Name;
            ViewBag.HasColumns = columns.Count > 0;

            var model = new BoardViewModel()
            {
                Board = board,
                Columns = columns,
                Colors = colors,
                Tasks = tasks.ToList()
            };

            return View(model);
        }

        [HttpPost]
        public void MoveTask(int taskId, int columnId)
        {
            var task = _taskRepository.Get(taskId);
            if (task.ColumnId == columnId) return;

            task.ColumnId = columnId;
            _taskRepository.Update(task);
        }

        [HttpPost]
        public ActionResult EditTask(int boardId, Task task)
        {
            if (ToDelete)
            {
                _taskRepository.Delete(task);
                return RedirectToAction("Index", new{id = boardId}).WithSuccess("Task Was Deleted");
            }

            if (!string.IsNullOrEmpty(task.Owner)) 
                task.Owner = task.Owner.Trim();

            if (task.Id == 0)
            {
                task.ColumnId = _columnRepository.List(boardId).First().Id;
                _taskRepository.Add(task);
                return RedirectToAction("Index", new { id = boardId }).WithSuccess("Task Was Added");
            }

            _taskRepository.Update(task);
            return RedirectToAction("Index", new { id = boardId }).WithSuccess("Task Was Saved");
        }

        [HttpGet]
        public ActionResult GetTask(string id)
        {
            var taskId = Convert.ToInt32(id.Substring(5));
            var task = _taskRepository.Get(taskId);
            var jsonResult = Json( new {
                        id = task != null ? task.Id : 0,
                        title = task != null ? task.Title : "",
                        text = task != null ? task.Description : "",
                        owner = task != null ? task.Owner : "",
                        columnId = task != null ? task.ColumnId : 0,
                        prio = task != null ? task.Prio : 100,
                        colorId = task != null ? task.ColorId : 1 }
            , JsonRequestBehavior.AllowGet);
            return jsonResult;
        }

        [HttpGet]
        public ActionResult GetOwners()
        {
            var owners = _taskRepository.List().Select(t => t.Owner).Distinct().ToArray();
            return Json(owners, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddColumn(Column column)
        {
            _columnRepository.Add(column);
            return RedirectToAction("Index", new { id = column.BoardId}).WithSuccess("Column Was Added");
        }
    }
}

KanbanProject/Controllers/HomeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using PlanningBoard.Infrastructure.Alerts;
using PlanningBoard.Model;
using PlanningBoard.ViewModels;

namespace PlanningBoard.Controllers
{
    public class HomeController : BaseController
    {
        private readonly IBoardRepository _boardRepository;
        private readonly IUserRerpository _userRerpository;

        public HomeController()
        {
            _boardRepository = new BoardRepository();
            _userRerpository = new UserRepository();
        }

        public ActionResult Index()
        {
            ViewBag.BoardName = "Kanban 4 U";

            var user = _userRerpository.GetUser();
            var boards = _boardRepository.List();
            var boardUsers = _boardRepository.BoardUsers(user.Id);

            var userboards = boards.Select(board => new UserBoardsViewModel()
            {
                BoardId = board.Id,
                BoardName = board.Name,
                IsAdmin = boardUsers.Any(b => b.BoardId == board.Id && b.IsAdmin)
            }).ToList();

            var model = new BoardsViewModel
            {
                Boards = userboards
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AddBoard(Board board)
        {
            if (board.Id == 0)
            {
                int boardId = _boardRepository.Add(new Board() {Name = board.Name});
                int userId = _userRerpository.GetUser().Id;
                _boardRepository.Add(new BoardUser() { BoardId = boardId, UserId = userId, IsAdmin = true });
                return RedirectToAction("Index").WithSuccess("New Board Added");
            }

            _boardRepository.Update(board);
            return RedirectToAction("Index").WithSuccess("Board Updated");
        }

        public ActionResult GetBoard(int id)
        {
            var board = _boardRepository.Get(id);

            var jsonResult = Json(
                board != null
                    ? new
                    {
                        id = board.Id,
                        name = board.Name
                    }
                    : new
                    {
                        id = 0,
                        name = "",
                    },
                JsonRequestBehavior.AllowGet);
            return jsonResult;
        }
    }
}

KanbanProject/Views/Home/Index.cshtml
@model PlanningBoard.ViewModels.BoardsViewModel

<div class="col-sm-12">
    @foreach (var board in Model.Boards)
    {
        <div class="col-sm-3 board smallshadow @Html.Raw(board.IsAdmin ? "isadmin" : "")" style="margin: 10px;" id="@board.BoardId">
            <a style="font-family: IndieFlower; font-size: x-large" href="@Url.Action("Index", "Board", new { id = board.BoardId })">@board.BoardName</a>
        </div>    
    }
</div>

<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST" action="@Url.Action("AddBoard")">
                <input type="hidden" id="boardId" name="id" />

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">
                        <span class="fa fa-pencil-square-o"></span>&nbsp;Add Board
                    </h4>
                </div>
                <div class="modal-body">
                    <div class="col-sm-12">
                        <label for="Name">Name:</label>
                        <input id="name" name="Name" class="form-control" style="font-size: x-large; height: 50px"
                            placeholder="New Board Name" data-val="true" data-val-required="Required" />
                        <span class="field-validation-valid" data-valmsg-for="Title" data-valmsg-replace="true"></span>
                    </div>
                </div>
                <div class="row"></div>
                <br />
                <div class="modal-footer">
                    <button id="taskSaveButton" value="Save" class="btn btn-primary"><span class="fa fa-save"></span>&nbsp;Save</button>
                    <button class="btn btn-default" data-dismiss="modal"><span class="fa fa-close"></span>&nbsp;Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section scripts
{

    <script>

        $(document).ready(function () {

            $("#NewBoardLink").click(function () {
                $("#addModal").modal();
            });

            $(".board .isadmin").dblclick(function () {
                var boardId = $(this).attr("id");

                //get the board from database
                $.ajax({
                    async: false,
                    type: 'GET',
                    url: '@Url.Action("GetBoard")/' + boardId + '?' + new Date().getTime(),
                    success: function (data) {
                        $("#boardId").val(data.id);
                        $("#name").val(data.name);
                    }
                });

                $("#addModal").modal();
                $("#name").focus();
            });


            // things to do when the new/edit dialog is displayed
            $("#addModal").on('shown.bs.modal', function () {
                $("#name").focus();
            });

            // things to do when the new/edit dialog is closed
            $("#addModal").on('hidden.bs.modal', function () {

            });
        });


    </script>
}

KanbanProject/Views/Shared/_Layout.cshtml
@using PlanningBoard.Infrastructure.Alerts
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>@ViewBag.Title - @ViewBag.BoardName.ToString()</title>
    <link href="~/favicon.ico?ver=1" rel="shortcut icon" type="image/x-icon" />
    <link href="~/favicon.png?ver=1" rel="icon" type="image/png" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                    <h3 class="logo" style="font-weight: normal">@ViewBag.BoardName.ToString()</h3>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (ViewBag.Controller == "Home")
                    {
                        <li><a id="NewBoardLink" style="cursor: pointer; font-family: IndieFlower">+ Add Board</a></li>
                    }
                    else
                    {
                        if (ViewBag.HasColumns != null && (bool)ViewBag.HasColumns == true)
                        {
                            <li><a id="NewTaskLink" style="cursor: pointer; font-family: IndieFlower">+ Add Task</a></li>
                        }
                        <li><a id="NewColumnLink" style="cursor: pointer; font-family: IndieFlower">+ Add Column</a></li>
                        <li><a href="@Url.Action("Index", "Home")" style="cursor: pointer; font-family: IndieFlower"># All Boards</a></li>
                    }
                </ul>
            </div>

        </div>
    </div>
    <div class="body-content">
        @RenderBody()
    </div>

    <footer class="text-center">
        <p>&copy; @DateTime.Now.Year - Made With PlanningBoard.Net</p>
        <p>Authenticated as @User.Identity.Name</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)

    @if (TempData.GetAlerts().Any())
    {
        if (TempData.GetAlerts().Any())
        {
            foreach (var alert in TempData.GetAlerts())
            {
        <script type="text/javascript">
            toastr.options.positionClass = "toast-bottom-right";
            @Html.Raw("toastr." + alert.AlertLevel + "('" + alert.Message + "');");
        </script>
       
            }
        }
    }
</body>
</html>